# Generated by Django 4.1.7 on 2023-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_image.png', upload_to='profile_images/'),
        ),
    ]
