# Generated by Django 4.1.7 on 2023-04-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_service_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='services',
        ),
        migrations.CreateModel(
            name='payment_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.payment')),
            ],
        ),
    ]
