# Generated by Django 4.1.7 on 2023-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_payment_service_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_cost',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
